### ISSUE TITLE
Segfault in listen gem

### ISSUE THREAD

**Issue by sshock** [boazsegev/iodine#74]
I'm not sure what changed to cause this to start happening, but I'm seeing it all the time now in both iodine 0.7.25 and 0.7.31.  The seg fault occurs immediately after starting rails.

```
=> Booting Rack
=> Rails 5.2.2.1 application starting in development on http://0.0.0.0:1338
=> Run `rails server -h` for more startup options
Plezi 0.16.4 as Middleware
Running Plezi version: 0.16.4
INFO: Listening on port 1338
INFO: Starting up Iodine:
 * Iodine 0.7.31
 * Ruby 2.6.2
 * facil.io 0.7.0.beta9 (kqueue)
 * 7 Workers X 8 Threads per worker.
 * Maximum 24560 open files / sockets per worker.
 * Master (root) process: 13517.

INFO: Server is running 7 workers X 8 threads with facil.io 0.7.0.beta9 (kqueue)
* Detected capacity: 24560 open file limit
* Root pid: 13517
* Press ^C to stop

INFO: 13534 is running.
INFO: 13536 is running.
INFO: 13538 is running.
INFO: 13540 is running.
INFO: 13542 is running.
INFO: 13544 is running.
INFO: 13546 is running.
I, [2019-05-20T14:27:38.668648 #13544]  INFO -- : Started GET "/endpoint" for 10.17.31.207 at 2019-05-20 14:27:38 -0600
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:53: [BUG] Segmentation fault at 0x000000010a3f5a3a
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0013 p:---- s:0062 e:000061 CFUNC  :open
c:0012 p:---- s:0059 e:000058 CFUNC  :entries
c:0011 p:0026 s:0051 e:000053 METHOD /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:53
c:0010 p:0005 s:0048 e:000047 METHOD /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/symlink_detector.rb:27
c:0009 p:0021 s:0042 e:000041 METHOD /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record.rb:103
c:0008 p:0070 s:0034 e:000033 METHOD /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record.rb:68
c:0007 p:0009 s:0028 e:000027 BLOCK  /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:76
c:0006 p:0017 s:0025 e:000024 METHOD /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:103
c:0005 p:0008 s:0018 e:000017 BLOCK  /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:76 [FINISH]
c:0004 p:---- s:0014 e:000013 CFUNC  :each
c:0003 p:0011 s:0010 e:000009 BLOCK  /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:75
c:0002 p:0007 s:0006 e:000005 BLOCK  /Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:75:in `block in start'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:75:in `each'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:76:in `block (2 levels) in start'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:103:in `_timed'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/adapter/base.rb:76:in `block (3 levels) in start'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record.rb:68:in `build'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record.rb:102:in `_fast_build_dir'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:18:in `children'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:53:in `_entries'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:53:in `entries'
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/listen-3.1.5/lib/listen/record/entry.rb:53:in `open'

-- Machine register context ------------------------------------------------
 rax: 0x000000010a3f5a38 rbx: 0x00007fdff35efac0 rcx: 0x0000700003cf00ac
 rdx: 0x0000000000000000 rdi: 0x00007fdff35efac0 rsi: 0x0000000000000001
 rbp: 0x0000700003cee250 rsp: 0x0000700003cede10  r8: 0x0000000000000001
  r9: 0x0000000000000006 r10: 0x0000000000000600 r11: 0x20f5dd11954000fa
 r12: 0x00007fdff35efac0 r13: 0x0000000000000000 r14: 0x0000000000000002
 r15: 0x000000010a3f5a3c rip: 0x00007fff63bd990a rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_vm_bugreport+0x82) [0x107596ab2]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_bug_context+0x1d8) [0x1073f0e28]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(sigsegv+0x51) [0x1074ffbc1]
/usr/lib/system/libsystem_platform.dylib(_sigtramp+0x1d) [0x7fff63bb6b5d]
/usr/lib/system/libsystem_trace.dylib(_os_log_preferences_refresh+0x4c) [0x7fff63bd990a]
/usr/lib/system/libsystem_trace.dylib(0x7fff63bda13d) [0x7fff63bda13d]
/usr/lib/system/libsystem_info.dylib(_gai_nat64_v4_address_requires_synthesis+0x62) [0x7fff63ae7692]
/usr/lib/system/libsystem_info.dylib(0x7fff63ae6aa0) [0x7fff63ae6aa0]
/usr/lib/system/libsystem_info.dylib(0x7fff63ac5847) [0x7fff63ac5847]
/usr/lib/system/libsystem_info.dylib(0x7fff63ac4f77) [0x7fff63ac4f77]
/usr/lib/system/libsystem_info.dylib(0x7fff63ac4e7d) [0x7fff63ac4e7d]
/usr/local/opt/postgresql/lib/libpq.5.dylib(connectDBStart+0x145) [0x10aada955]
/usr/local/opt/postgresql/lib/libpq.5.dylib(0x10aad9b5b) [0x10aad9b5b]
/usr/local/opt/postgresql/lib/libpq.5.dylib(0x10aad9afe) [0x10aad9afe]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/pg-1.1.4/lib/pg_ext.bundle(gvl_PQconnectdb_skeleton+0x11) [0x10aa99d11]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(call_without_gvl+0xb0) [0x10753c420]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/pg-1.1.4/lib/pg_ext.bundle(gvl_PQconnectdb+0x2d) [0x10aa99ced]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/pg-1.1.4/lib/pg_ext.bundle(pgconn_init+0x79) [0x10aa9ee99]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(vm_call0_body+0x256) [0x10757bae6]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_call0+0xf5) [0x107591ae5]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_funcallv+0x31) [0x10757a021]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_class_s_new+0x29) [0x10747b629]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(vm_call_cfunc+0x15b) [0x107589d7b]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(vm_exec_core+0x33df) [0x107572a5f]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_vm_exec+0xaa2) [0x107584932]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_call0+0xf5) [0x107591ae5]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_funcallv+0x31) [0x10757a021]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_class_s_new+0x29) [0x10747b629]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(vm_call_cfunc+0x15b) [0x107589d7b]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(vm_exec_core+0x33df) [0x107572a5f]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_vm_exec+0xaa2) [0x107584932]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_call0+0xf5) [0x107591ae5]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_funcallv+0x31) [0x10757a021]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_protect+0x154) [0x1073fc944]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(iodine_call2+0x65) [0x10aa2fe05]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(iodine_handle_request_in_GVL+0xf40) [0x10aa36f10]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(rb_thread_call_with_gvl+0x57) [0x10753cba7]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(iodine_enterGVL+0x39) [0x10aa2fc89]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(on_rack_upgrade+0x5a) [0x10aa3485a]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(http_on_request_handler______internal+0x368) [0x10aa1bdc8]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(http1_on_request+0x1a) [0x10aa1a5ca]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(http1_fio_parser_fn+0xabb) [0x10aa1b9bb]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(http1_consume_data+0x17a) [0x10aa1a4fa]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(deferred_on_data+0x1a3) [0x10a9cd393]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(fio_defer_perform_single_task_for_queue+0x19c) [0x10a9cc81c]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(fio_defer_cycle+0x60) [0x10a9e16d0]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(defer_thread_start+0x1b) [0x10aa33c8b]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(call_without_gvl+0xb0) [0x10753c420]
/Users/sshock/.rvm/gems/ruby-2.6.2@myproj/gems/iodine-0.7.31/lib/iodine/iodine.bundle(defer_thread_inGVL+0x58) [0x10aa33c58]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(thread_do_start+0x248) [0x107544868]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(thread_start_func_2+0x1f6) [0x1075442e6]
/Users/sshock/.rvm/rubies/ruby-2.6.2/lib/libruby.2.6.dylib(thread_start_func_1+0x117) [0x107543f27]
/usr/lib/system/libsystem_pthread.dylib(_pthread_body+0x7e) [0x7fff63bbf2eb]
/usr/lib/system/libsystem_pthread.dylib(0x7fff63bc2249) [0x7fff63bc2249]
```

**Comment by boazsegev** [comment]
Hi @sshock ,

Thank you for opening this issue.

I understand your concern and want to help you resolve this issue as fast as possible. However, I can't recreate the issue on my machine, since iodine runs my Rack applications without a hitch.

My only (current) guess is that this might be a naming collision with a gem in your specific stack (or it could be another gem is seg-faulting).

Is there a way I could get a small app that would allow me to recreate the issue on my machine / VM?

Thanks!
   Bo.

**Comment by sshock** [comment]
Hi @boazsegev 

I tried tracking it down some my by bisecting the code, without any luck.  Also, I'm doubtful that I can reproduce it with a new small rails app.

Good news though.  The crash definitely is in the listen gem, and turns out I don't actually need the listen gem, so I just removed that and I'm fine now.

**Comment by boazsegev** [comment]
Thank you for the update!

I'm very happy to know iodine is working as expected :)

If anything else comes up, please feel free to let me know.

Kindly,
   Bo.
